version: 2

project_name: muna-image-google

builds:
  - id: muna-image-google
    binary: muna-image-google
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    ids:
      - muna-image-google
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  name_template: "{{ .Tag }}"
  replace_existing_artifacts: true
