package cmd

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	"google.golang.org/genai"
)

func TestFetchAllModels_MultiPages(t *testing.T) {
	requestCount := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestCount++
		if r.URL.Path != "/v1beta/models" {
			t.Fatalf("unexpected path: %s", r.URL.Path)
		}
		if requestCount == 1 {
			if r.URL.Query().Get("pageToken") != "" {
				t.Fatalf("first request should not include pageToken")
			}
			_ = json.NewEncoder(w).Encode(map[string]any{
				"models":        []map[string]any{{"name": "models/a", "displayName": "A"}},
				"nextPageToken": "page-2",
			})
			return
		}
		if r.URL.Query().Get("pageToken") != "page-2" {
			t.Fatalf("unexpected pageToken: %s", r.URL.Query().Get("pageToken"))
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"models": []map[string]any{
				{"name": "models/b", "displayName": "B"},
				{"name": "models/c", "displayName": "C"},
			},
			"nextPageToken": "",
		})
	}))
	defer server.Close()

	client := newTestGenAIClient(t, server)
	models, err := fetchAllModels(context.Background(), client)
	if err != nil {
		t.Fatalf("expected nil error, got %v", err)
	}
	if len(models) != 3 {
		t.Fatalf("expected 3 models, got %d", len(models))
	}
	if models[0].Name != "models/a" || models[2].Name != "models/c" {
		t.Fatalf("unexpected model list: %+v", models)
	}
}

func TestFetchAllModels_NextPageError(t *testing.T) {
	requestCount := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requestCount++
		if requestCount == 1 {
			_ = json.NewEncoder(w).Encode(map[string]any{
				"models":        []map[string]any{{"name": "models/a"}},
				"nextPageToken": "page-2",
			})
			return
		}
		w.WriteHeader(http.StatusInternalServerError)
		_, _ = w.Write([]byte(`{"error":{"code":500,"message":"boom"}}`))
	}))
	defer server.Close()

	client := newTestGenAIClient(t, server)
	_, err := fetchAllModels(context.Background(), client)
	if err == nil {
		t.Fatalf("expected error from next page request")
	}
}

func TestGenerateOnce_Success(t *testing.T) {
	imageBytes := []byte{1, 2, 3, 4}
	encoded := base64.StdEncoding.EncodeToString(imageBytes)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Fatalf("unexpected method: %s", r.Method)
		}
		if filepath.Base(r.URL.Path) != "test-model:generateContent" {
			t.Fatalf("unexpected path: %s", r.URL.Path)
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"candidates": []map[string]any{
				{
					"content": map[string]any{
						"parts": []map[string]any{
							{"inlineData": map[string]any{"mimeType": "image/png", "data": encoded}},
						},
					},
				},
			},
		})
	}))
	defer server.Close()

	originalModel, originalOut, originalTimeout, originalVerbose := modelFlag, outFlag, timeoutFlag, verboseFlag
	modelFlag = "test-model"
	outFlag = t.TempDir()
	timeoutFlag = 2 * time.Second
	verboseFlag = false
	t.Setenv("MUNA_IMAGE_GOOGLE_BASE_URL", server.URL)
	t.Cleanup(func() {
		modelFlag, outFlag, timeoutFlag, verboseFlag = originalModel, originalOut, originalTimeout, originalVerbose
	})

	absPath, finishMessage, err := generateOnce(context.Background(), "test-key", "test-model", "hello", nil, &genai.GenerateContentConfig{}, 7)
	if err != nil {
		t.Fatalf("expected nil error, got %v", err)
	}
	if finishMessage != "" {
		t.Fatalf("expected empty finish message, got %s", finishMessage)
	}
	if !filepath.IsAbs(absPath) {
		t.Fatalf("expected absolute path, got %s", absPath)
	}
	written, err := os.ReadFile(absPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}
	if string(written) != string(imageBytes) {
		t.Fatalf("unexpected generated bytes: %v", written)
	}
}

func TestGenerateOnce_NoImageUsesRawFinishMessage(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if filepath.Base(r.URL.Path) != "test-model:generateContent" {
			t.Fatalf("unexpected path: %s", r.URL.Path)
		}
		_, _ = io.WriteString(w, `{
			"candidates": [
				{
					"finishMessage": "raw-finish-message",
					"content": {
						"parts": [
							{"text": "only text"}
						]
					}
				}
			]
		}`)
	}))
	defer server.Close()

	originalModel, originalOut, originalTimeout, originalVerbose := modelFlag, outFlag, timeoutFlag, verboseFlag
	modelFlag = "test-model"
	outFlag = t.TempDir()
	timeoutFlag = 2 * time.Second
	verboseFlag = false
	t.Setenv("MUNA_IMAGE_GOOGLE_BASE_URL", server.URL)
	t.Cleanup(func() {
		modelFlag, outFlag, timeoutFlag, verboseFlag = originalModel, originalOut, originalTimeout, originalVerbose
	})

	absPath, finishMessage, err := generateOnce(context.Background(), "test-key", "test-model", "hello", nil, &genai.GenerateContentConfig{}, 7)
	if !errors.Is(err, errNoImage) {
		t.Fatalf("expected errNoImage, got %v", err)
	}
	if absPath != "" {
		t.Fatalf("expected empty output path, got %s", absPath)
	}
	if finishMessage != "raw-finish-message" {
		t.Fatalf("unexpected finish message: %s", finishMessage)
	}
}

func newTestGenAIClient(t *testing.T, server *httptest.Server) *genai.Client {
	t.Helper()

	client, err := genai.NewClient(context.Background(), &genai.ClientConfig{
		APIKey:     "test-api-key",
		HTTPClient: server.Client(),
		HTTPOptions: genai.HTTPOptions{
			BaseURL:    server.URL,
			APIVersion: "v1beta",
		},
	})
	if err != nil {
		t.Fatalf("failed to create genai client: %v", err)
	}
	return client
}
